// GENERATED FILE - DO NOT EDIT BY HAND.
// Generated by scripts/generate-flutter.ts from data/icons/*.
// Regenerate with `pnpm run generate:flutter`.

import 'package:flutter/widgets.dart';

import 'src/icon_base.dart';

/// Typed accessors for every Zag icon.
///
/// Each accessor renders precompiled `.vg` bytecode through [ZagIconBase]
/// and supports Reicon-style weight variants.
abstract final class ZagIcons {
  ZagIcons._();

  /// ArrowLeft icon.
  ///
  /// Sources: `data/icons/outline/arrowLeft.svg` and
  /// `data/icons/filled/arrowLeft.svg`.
  static Widget arrowLeft({
    IconWeight weight = IconWeight.outline,
    double size = 24.0,
    Color? color,
    String? semanticLabel,
    Key? key,
  }) {
    return ZagIconBase(
      key: key,
      name: 'arrowLeft',
      weight: weight,
      size: size,
      color: color,
      semanticLabel: semanticLabel,
    );
  }

  /// ArrowRight icon.
  ///
  /// Sources: `data/icons/outline/arrowRight.svg` and
  /// `data/icons/filled/arrowRight.svg`.
  static Widget arrowRight({
    IconWeight weight = IconWeight.outline,
    double size = 24.0,
    Color? color,
    String? semanticLabel,
    Key? key,
  }) {
    return ZagIconBase(
      key: key,
      name: 'arrowRight',
      weight: weight,
      size: size,
      color: color,
      semanticLabel: semanticLabel,
    );
  }

  /// Heart icon.
  ///
  /// Sources: `data/icons/outline/heart.svg` and
  /// `data/icons/filled/heart.svg`.
  static Widget heart({
    IconWeight weight = IconWeight.outline,
    double size = 24.0,
    Color? color,
    String? semanticLabel,
    Key? key,
  }) {
    return ZagIconBase(
      key: key,
      name: 'heart',
      weight: weight,
      size: size,
      color: color,
      semanticLabel: semanticLabel,
    );
  }

  /// Home icon.
  ///
  /// Sources: `data/icons/outline/home.svg` and
  /// `data/icons/filled/home.svg`.
  static Widget home({
    IconWeight weight = IconWeight.outline,
    double size = 24.0,
    Color? color,
    String? semanticLabel,
    Key? key,
  }) {
    return ZagIconBase(
      key: key,
      name: 'home',
      weight: weight,
      size: size,
      color: color,
      semanticLabel: semanticLabel,
    );
  }
}
