// GENERATED FILE - DO NOT EDIT BY HAND.
// Generated by scripts/generate-flutter.ts from data/illustrations/*.
// Regenerate with `pnpm run generate:flutter`.

import 'package:flutter/widgets.dart';

import 'src/illustration_base.dart';

/// Typed accessors for every Zag illustration.
///
/// Illustrations keep their original multi-color fills and gradients; no
/// tinting color filter is applied.
abstract final class ZagIllustrations {
  ZagIllustrations._();

  /// EmptyState illustration.
  ///
  /// Source: `data/illustrations/emptyState.svg`.
  static Widget emptyState({
    double? width,
    double? height,
    BoxFit fit = BoxFit.contain,
    String? semanticLabel,
    Key? key,
  }) {
    return ZagIllustrationBase(
      key: key,
      name: 'emptyState',
      width: width,
      height: height,
      fit: fit,
      semanticLabel: semanticLabel,
    );
  }
}
