/**
 * Generates the Flutter icon package artifacts from source SVGs.
 *
 * - Compiles every SVG in data/icons/{outline,filled} and data/illustrations
 *   into vector_graphics bytecode (.vg) via the Dart CLI:
 *     dart run vector_graphics_compiler -i <input.svg> -o <output.vg>
 * - Emits strongly typed Dart accessor classes at:
 *     packages/icons_flutter/lib/icons.dart          (ZagIcons.*)
 *     packages/icons_flutter/lib/illustrations.dart  (ZagIllustrations.*)
 */
import { spawnSync } from 'node:child_process';
import { mkdir, readdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = fileURLToPath(new URL('..', import.meta.url));
const dataRoot = path.join(repoRoot, 'data');
const flutterRoot = path.join(repoRoot, 'packages', 'icons_flutter');
const flutterAssets = path.join(flutterRoot, 'assets');
const flutterLib = path.join(flutterRoot, 'lib');

interface SvgFile {
  stem: string;
  file: string;
}

/* ------------------------------------------------------------------ */
/* Helpers                                                             */
/* ------------------------------------------------------------------ */

function stemOf(fileName: string): string {
  return fileName.replace(/\.svg$/i, '');
}

function toPascalCase(stem: string): string {
  return stem
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

/** Dart identifier (lowerCamelCase) used for generated methods. */
function toCamelCase(stem: string): string {
  const pascal = toPascalCase(stem);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

function escapeDoc(text: string): string {
  return text.replace(/\]/g, '\\]').replace(/\[/g, '\\[');
}

function run(command: string, args: string[], options: { cwd?: string } = {}): void {
  const result = spawnSync(command, args, {
    stdio: 'inherit',
    shell: true,
    ...options,
  });
  if (result.error) {
    throw new Error(`Failed to spawn "${command}": ${result.error.message}`);
  }
  if (result.status !== 0) {
    throw new Error(
      `"${command} ${args.join(' ')}" exited with code ${result.status ?? 'unknown'}.`,
    );
  }
}

function assertDartToolchain(): void {
  const probe = spawnSync('dart', ['--version'], { stdio: 'pipe', shell: true });
  if (probe.error || probe.status !== 0) {
    console.error(
      '[generate-flutter] The Dart SDK is required but was not found on PATH.\n' +
        '  Install it via https://docs.flutter.dev/get-started/install or\n' +
        '  https://dart.dev/get-dart, then re-run `pnpm run generate:flutter`.',
    );
    process.exit(1);
  }
}

async function listSvgFiles(dir: string): Promise<SvgFile[]> {
  try {
    const entries = await readdir(dir);
    return entries
      .filter((entry) => entry.toLowerCase().endsWith('.svg'))
      .sort()
      .map((file) => ({ stem: stemOf(file), file }));
  } catch {
    return [];
  }
}

interface CompileJob {
  inputSvg: string;
  outputVg: string;
}

function compileBatch(jobs: CompileJob[]): void {
  // `dart run` must execute inside the package so vector_graphics_compiler
  // is resolved from its dev_dependencies.
  for (const job of jobs) {
    run(
      'dart',
      ['run', 'vector_graphics_compiler', '-i', job.inputSvg, '-o', job.outputVg],
      { cwd: flutterRoot },
    );
  }
}

/* ------------------------------------------------------------------ */
/* Dart templates                                                      */
/* ------------------------------------------------------------------ */

function iconsTemplate(entries: Array<{ camel: string; pascal: string; doc: string }>): string {
  const methods = entries
    .map(
      (entry) => `  /// ${escapeDoc(entry.doc)}
  ///
  /// Sources: \`data/icons/outline/${entry.camel}.svg\` and
  /// \`data/icons/filled/${entry.camel}.svg\`.
  static Widget ${entry.camel}({
    IconWeight weight = IconWeight.outline,
    double size = 24.0,
    Color? color,
    String? semanticLabel,
    Key? key,
  }) {
    return ZagIconBase(
      key: key,
      name: '${entry.camel}',
      weight: weight,
      size: size,
      color: color,
      semanticLabel: semanticLabel,
    );
  }
`,
    )
    .join('\n');

  return `// GENERATED FILE - DO NOT EDIT BY HAND.
// Generated by scripts/generate-flutter.ts from data/icons/*.
// Regenerate with \`pnpm run generate:flutter\`.

import 'package:flutter/widgets.dart';

import 'src/icon_base.dart';

/// Typed accessors for every Zag icon.
///
/// Each accessor renders precompiled \`.vg\` bytecode through [ZagIconBase]
/// and supports Reicon-style weight variants.
abstract final class ZagIcons {
  ZagIcons._();

${methods}}
`;
}

function illustrationsTemplate(
  entries: Array<{ camel: string; pascal: string; doc: string }>,
): string {
  const methods = entries
    .map(
      (entry) => `  /// ${escapeDoc(entry.doc)}
  ///
  /// Source: \`data/illustrations/${entry.camel}.svg\`.
  static Widget ${entry.camel}({
    double? width,
    double? height,
    BoxFit fit = BoxFit.contain,
    String? semanticLabel,
    Key? key,
  }) {
    return ZagIllustrationBase(
      key: key,
      name: '${entry.camel}',
      width: width,
      height: height,
      fit: fit,
      semanticLabel: semanticLabel,
    );
  }
`,
    )
    .join('\n');

  return `// GENERATED FILE - DO NOT EDIT BY HAND.
// Generated by scripts/generate-flutter.ts from data/illustrations/*.
// Regenerate with \`pnpm run generate:flutter\`.

import 'package:flutter/widgets.dart';

import 'src/illustration_base.dart';

/// Typed accessors for every Zag illustration.
///
/// Illustrations keep their original multi-color fills and gradients; no
/// tinting color filter is applied.
abstract final class ZagIllustrations {
  ZagIllustrations._();

${methods}}
`;
}

/* ------------------------------------------------------------------ */
/* Main                                                                */
/* ------------------------------------------------------------------ */

async function main(): Promise<void> {
  assertDartToolchain();

  /* ---------------- Compile SVG -> .vg bytecode ---------------- */

  await rm(path.join(flutterAssets, 'icons'), { recursive: true, force: true });
  await rm(path.join(flutterAssets, 'illustrations'), { recursive: true, force: true });

  const outlineDir = path.join(dataRoot, 'icons', 'outline');
  const filledDir = path.join(dataRoot, 'icons', 'filled');
  const illustrationsDir = path.join(dataRoot, 'illustrations');

  const outlineFiles = await listSvgFiles(outlineDir);
  const filledFiles = await listSvgFiles(filledDir);
  const filledStems = new Set(filledFiles.map((entry) => entry.stem));

  const iconJobs: CompileJob[] = [];
  const iconEntries: Array<{ camel: string; pascal: string; doc: string }> = [];

  for (const entry of outlineFiles) {
    if (!filledStems.has(entry.stem)) {
      console.warn(
        `[generate-flutter] Skipping icon "${entry.stem}": missing filled variant.`,
      );
      continue;
    }
    const outlineOut = path.join(flutterAssets, 'icons', 'outline', `${entry.stem}.vg`);
    const filledOut = path.join(flutterAssets, 'icons', 'filled', `${entry.stem}.vg`);
    await mkdir(path.dirname(outlineOut), { recursive: true });
    await mkdir(path.dirname(filledOut), { recursive: true });
    iconJobs.push({ inputSvg: path.join(outlineDir, entry.file), outputVg: outlineOut });
    iconJobs.push({ inputSvg: path.join(filledDir, entry.file), outputVg: filledOut });
    iconEntries.push({
      camel: toCamelCase(entry.stem),
      pascal: toPascalCase(entry.stem),
      doc: `${toPascalCase(entry.stem)} icon.`,
    });
  }

  for (const entry of filledFiles) {
    if (!outlineFiles.some((candidate) => candidate.stem === entry.stem)) {
      console.warn(
        `[generate-flutter] Skipping icon "${entry.stem}": missing outline variant.`,
      );
    }
  }

  const illustrationJobs: CompileJob[] = [];
  const illustrationEntries: Array<{ camel: string; pascal: string; doc: string }> = [];

  const illustrationFiles = await listSvgFiles(illustrationsDir);
  for (const entry of illustrationFiles) {
    const out = path.join(flutterAssets, 'illustrations', `${entry.stem}.vg`);
    await mkdir(path.dirname(out), { recursive: true });
    illustrationJobs.push({
      inputSvg: path.join(illustrationsDir, entry.file),
      outputVg: out,
    });
    illustrationEntries.push({
      camel: toCamelCase(entry.stem),
      pascal: toPascalCase(entry.stem),
      doc: `${toPascalCase(entry.stem)} illustration.`,
    });
  }

  console.log('[generate-flutter] Resolving Dart dependencies (dart pub get)...');
  run('dart', ['pub', 'get'], { cwd: flutterRoot });

  const total = iconJobs.length + illustrationJobs.length;
  console.log(
    `[generate-flutter] Compiling ${total} SVG file(s) to vector_graphics bytecode...`,
  );
  compileBatch(iconJobs);
  compileBatch(illustrationJobs);

  /* ---------------- Emit typed Dart accessors ---------------- */

  await writeFile(
    path.join(flutterLib, 'icons.dart'),
    iconsTemplate(iconEntries),
    'utf8',
  );
  await writeFile(
    path.join(flutterLib, 'illustrations.dart'),
    illustrationsTemplate(illustrationEntries),
    'utf8',
  );

  // Keep generated Dart canonically formatted; non-fatal if formatting hiccups.
  const formatted = spawnSync('dart', ['format', 'lib'], {
    cwd: flutterRoot,
    stdio: 'pipe',
    shell: true,
  });
  if (formatted.status !== 0) {
    console.warn('[generate-flutter] `dart format lib` reported issues; continuing.');
  }

  console.log(
    `[generate-flutter] Wrote lib/icons.dart (${iconEntries.length} icon(s)) and ` +
      `lib/illustrations.dart (${illustrationEntries.length} illustration(s)).`,
  );
}

main().catch((error) => {
  console.error('[generate-flutter] Failed:', error);
  process.exitCode = 1;
});
